### ISSUE TITLE
USER STORY: Program Model

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#11]
As a **developer**, I can create data model classes for programs so that structure my data effectively develop relationships between each type

**Acceptance Criteria:**
1. Each model is planned out with necessary fields
2. Each model is named according to its function
3. Model relationships are clearly stated with FK or M2M relationships

**Tasks**
- [x] Create a program model
- [x] List all necessary fields
- [x] Create custom methods if required
- [x] Define its __str__ name

**Comment by DarrachBarneveld** [comment]
Program and associated Module class created. Admin registered
