### ISSUE TITLE
 USER STORY: Subscription Model

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#12]
As a **developer**, I can create data model classes for subscriptions so that structure my data effectively develop relationships between each type

**Acceptance Criteria:**
1. Each model is planned out with necessary fields
2. Each model is named according to its function
3. Model relationships are clearly stated with FK or M2M relationships

**Tasks**
- [ ] Create a subscriptions model
- [ ] List all necessary fields
- [ ] Create custom methods if required
- [ ] Define its __str__ name

**Comment by DarrachBarneveld** [comment]
Subscription model created and linked to User Profile. Admin registered
