### ISSUE TITLE
USER STORY: Admin Classes

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#15]
As a **site owner**, I can see all my models and data through an admin portal so I can effectively manage my data through CRUD requests

**Acceptance Criteria:**
1. Each relative module has an admin class created in admin.py
2. Associated models are linked with inline or field sets
3. Only required model data is shown
4. All data can be manipulated through the admin portal

**Tasks**
- [x] Create admin classes for each required data model
- [x] Exclude/Include necessary fields from models
- [x] Create readonly fields for data not required for manipulation
- [x] Present data in its appropriate category

**Comment by DarrachBarneveld** [comment]
All relevant models are editable from the admin panel via creation of admin class models.
