### ISSUE TITLE
USER STORY: Sign Up / Login 

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#16]
As a **User**, I can create or login into my account so that I can retrieve my preexisting secure data 

**Acceptance Criteria:**
1. User sign-up/login process should be easy to follow and intuitive.
2. The sign-up/login page should have clear error handling and validation for user input.
3. User registration data must be securely stored and processed.

**Tasks**
- [x] Create an authentication button dropdown in the Navbar
- [x] Register and Login templates are created
- [x]  Implement error handling and user feedback
- [x]  Style the form in accordance with the current theming 
- [ ]  Ensure a user profile is created that is linked to the auth user
- [x] Notify user on a successful registration

**Comment by DarrachBarneveld** [comment]
Users can view a login/register page and create an account that auto links to a userprofile model.
