### ISSUE TITLE
USER STORY: Mock Data 

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#18]
As a **developer**, I can create mock data so that the final application has products, programs and other required models immediately created

**Acceptance Criteria:**
1. A fixture folder exists
2. Fixture folder has necessary json files for each model to be created
3. Fixture models contain all relevant data
4. A media folder exists with all relevant imagery

**Tasks**
- [x] Create a fixture folder
- [x] Insert category json file with all category data
- [x] Insert product json file with all product data
- [x] Insert program json file with all program data
- [x] Insert module json file with all module data
- [x] Insert subscription json file with all subscription data
- [x] Include all necessary product/program images

**Comment by DarrachBarneveld** [comment]
Fixture folder implemented, all model data.json files loaded onto DB. All images located in media file
