### ISSUE TITLE
User Story: Base Template / Styles

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#19]
As a **developer**, I can have a base template so that all other templates can inherit from it and keep consistant theming

**Acceptance Criteria:**
1. Base template exists
2. Contains all necessary block content
3. All necessary scripts are included
4. All website wide includes are in a separate folder
5. All website wide css/js is contained in a static folder

**Tasks**
- [x] Create a base templates folder
- [x] Create a static folder with js/css
- [x] Create an includes folder
- [x] Base.html contains all required scripts
- [x] Contains separated block content for easy page manipulation/inheritance 
- [x] All css/media is linked
- [x] Folder is in root directory
- [x] settings.py is correctly setup for template renders

**Comment by DarrachBarneveld** [comment]
Initial base template created and configured dirs in settings.py
