### ISSUE TITLE
User Story: Home Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#20]
As a **User**, I can visit the home page so that I can get a understanding of what the website content is about and navigate through

**Acceptance Criteria:**
1. Home page shows the purpose of the website
2. All copy and content is relevant to the website
3. Consistant branding is used
4. Home page is gives intuitive navigation

**Tasks**
- [x] Home.html template created
- [x] Urls and views are corrected linked
- [x] All theming is consistant 
- [x] Create intuitive navigation buttons within the copy
- [x] Create imagery is used
- [x] Copy is carefully represented and structured

**Comment by DarrachBarneveld** [comment]
Home page fully created as per wireframe
