### ISSUE TITLE
User Story: Category Model

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#21]
As a **developer**, I can create data model classes for categories so that structure my data effectively develop relationships between each type

**Acceptance Criteria:**
1. Each model is planned out with necessary fields
2. Each model is named according to its function
3. Model relationships are clearly stated with FK or M2M relationships

**Tasks**
- [x] Create a categories model
- [x] List all necessary fields
- [x] Create custom methods if required
- [x] Define its __str__ name

**Comment by DarrachBarneveld** [comment]
Category model created and admin register configured
