### ISSUE TITLE
User Story: Product Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#22]
As a **User**, I can visit the product page so that I can view all products available to purchase

**Acceptance Criteria:**
1. Product page is styled in accordance with theme
2. Products are clearly visible on all devices
3. Products can be filtered based on queries 

**Tasks**
- [x] products.html template created
- [x] Urls and views are corrected linked
- [x] All theming is consistant 
- [x] Filter products based on price, category and rating
- [x] Products link to product detail page

**Comment by DarrachBarneveld** [comment]
Product page is completed as planned
