### ISSUE TITLE
User Story Product Card

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#23]
As a **User**, I can see  standardised product preview card, providing key information at a glance so I can quickly make a decision

**Acceptance Criteria:**

1. Each product is represented by a standardised article preview card.
2. The product card includes essential information, such as price, rating and image.
3. The card has a short excerpt of marketing copy to sell the product.
4. Users can click on the product card access the full product details page.
6. The layout of the product card is responsive and optimised for various screen sizes

**Tasks**
- [x] Create a standardised template for rendering product cards. 
- [x] Configure the preview card to include a thumbnail image representing the product
- [x] Ensure that the preview card links to the full product details page
- [x] Ensure all rating, price and excerpt are displayed in an easily digestible manner.
- [x] Design and implement a responsive layout

**Comment by DarrachBarneveld** [comment]
Product card styled and displays relevant data - links to product detail page
