### ISSUE TITLE
User Story: Product Detail Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#24]
As a **User**, I can visit the product detail page so that I can get more information on the product and add it to my card

**Acceptance Criteria:**
1. Product detail page is styled in accordance with theme
2. Products information and image is rendered
3. Product can be added to the cart

**Tasks**
- [x] product_detail.html template created
- [x] Urls and views are corrected linked
- [x] Product is dynamically rendered based on params
- [x] All Product information is clearly legible 
- [x] Page is fully responsive 
- [x] Create an add to cart button
- [x] Create an increments button to add multiple products to card

**Comment by DarrachBarneveld** [comment]
Product detail page is displayed as per wireframes. All functionality performs as intended
