### ISSUE TITLE
User Story: Searchbar / Filter

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#25]
As a User, I can use a search bar to narrow down search results so that I can quickly find products/programs tailored to me

**Acceptance Criteria:**
1. The search bar is displayed at the top of product/program pages
2 .When I enter a keyword or phrase into the search bar and press enter, relevant results are displayed.
3. The search results are sorted based on relevance to my query.
4. I can refine my search using filters such as category, price or rating

**Tasks**
- [x] Implement search bar UI that remains consistant to theme
- [x] Connect search bar to product/program views and implement query functionality
- [x] Implement filters for search results based on rating, sale and price
- [x] Store all query options within url so it can be saved in history
- [x] Render all products/programs based on results

**Comment by DarrachBarneveld** [comment]
Search bar functionality completed. Search bar a resusable component for both product/program page
