### ISSUE TITLE
User Story: Program Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#26]
As a **User**, I can visit the program page so that I can view all program available to enroll in

**Acceptance Criteria:**
1. Program page is styled in accordance with theme
2. Programs are clearly visible on all devices
3. Programs can be filtered based on queries 

**Tasks**
- [x] programs.html template created
- [x] Urls and views are corrected linked
- [x] All theming is consistant 
- [x] Filter products based on price, category and rating
- [x] Programs link to program detail page

**Comment by DarrachBarneveld** [comment]
Program page constructed as per wireframes
