### ISSUE TITLE
User Story: Program Detail Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#27]
As a **User**, I can visit the program detail page so that I can get more information on the program and add it to my cart

**Acceptance Criteria:**
1. Program detail page is styled in accordance with theme
2. Programs information and image is rendered
3. Programs can be added to the cart

**Tasks**
- [x] program_detail.html template created
- [x] Urls and views are corrected linked
- [x] Program is dynamically rendered based on params
- [x] All Program information is clearly legible 
- [x] Page is fully responsive 
- [x] Create an add to cart button
- [x] Ensure program can only be added once to cart

**Comment by DarrachBarneveld** [comment]
Program detail page displayed as planned. All functionality installed
