### ISSUE TITLE
User Story: Program Card

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#28]
As a **User**, I can see  standardised program preview card, providing key information at a glance so I can quickly make a decision

**Acceptance Criteria:**

1. Each program is represented by a standardised article preview card.
2. The program card includes essential information, such as price, rating and image, difficulty and length.
3. The card has a short excerpt of marketing copy to sell the program.
4. Users can click on the program card access the full product details page.
6. The layout of the program card is responsive and optimised for various screen sizes

**Tasks**
- [x] Create a standardised template for rendering program cards. 
- [x] Configure the preview card to include a thumbnail image representing the program
- [x] Ensure that the preview card links to the full program details page
- [x] Ensure all rating, price and excerpt, difficult and length are displayed in an easily digestible manner.
- [x] Design and implement a responsive layout

**Comment by DarrachBarneveld** [comment]
Program card styled and displayed all relevant details. Links to program detail page
