### ISSUE TITLE
User Story: Add and Remove to cart

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#29]
As a **User**, I can add and remove items from my shopping cart so that I can manage my purchases easily and efficiently.

**Acceptance Criteria:**
1. I can click on the "Add to Cart" button next to an item to add it to my cart.
2. The quantity of each item in the cart is displayed and can be adjusted if its a product
3. I can remove items from my cart by clicking on the "Remove" or "Delete" button next to each item.
4. 

**Tasks**
- [x] Implement an add to cart functionality.
- [x] Implement a remove to cart functionality.
- [x] Save the context of the cart so that all areas of the application have access to cart details
- [x] Update the UI when adding items to cart 
- [x] Add notifications when adding and removing items from cart

**Comment by DarrachBarneveld** [comment]
Add, update and remove from cart functionality works as intended
