### ISSUE TITLE
USER STORY: Connect database and s3 storage and stripe

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#3]
As a developer I can connect database, static/media storage and stripe payments so that data is accessible on deployment and payments are configured early

**Tasks**
- [x] Configure Django's settings to connect to database.
- [x] Configure settings for ElephantSQL
- [x] Configure settings for static files and media directory roots
- [x] Create superuser for admin panel
- [x] Migrate DB changes
- [x] Link AWS storage to settings.py and env.py
- [x] Link Stripe authentication to env.py
- [x] Store all config vars in heroku

**Comment by DarrachBarneveld** [comment]
All required configuration for AWS, Stripe and ElephantSQL created
