### ISSUE TITLE
User Story: CRUD Notifications

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#32]
As a **User**, I can receive notification messages whenever a CRUD (Create, Read, Update, Delete) action is taken, so that I am informed about the outcome of my actions and any relevant changes.

**Acceptance Criteria:**
1. Users receive a notification on a create action
2. Users receive a notification on a update action
3. Users receive a notification on a delete action
4. Pop up toast notifications are displayed in a styled modal

**Tasks**
- [x] Create notifications for create action
- [x] Create notifications for update actions
- [x] Create notifications for delete actions
- [x] Style a modal in accordance with theming
- [x] Display the outcome of the action on the popup

**Comment by DarrachBarneveld** [comment]
All CRUD requests update user with outcome notification
