### ISSUE TITLE
User Story: Subscription Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#33]
As a **User**, I can visit the subscription page so that I can view all subscriptions available 

**Acceptance Criteria:**
1. Subscription page is styled in accordance with theme
2. Subscription are clearly visible on all devices
3. Subscription can be filtered based on queries 
4. Only Authenticated users can become members

**Tasks**
- [x] subscription.html template created
- [x] Urls and views are corrected linked
- [x] All theming is consistant 
- [x] Require login before subscriptions are visible

**Comment by DarrachBarneveld** [comment]
Subscription template, views and urls created. Add to cart feature implemented
