### ISSUE TITLE
User Story: Checkout Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#34]
As a **User**, I can view a checkout page so that I can get a run down of items and my total charge

**Acceptance Criteria:**
1. Users can see a summary of items in the cart
2. The layout adheres to theming and is fully responsive
3. A total charge amount is listed 
4. Individual item price amounts are listed

**Tasks**
- [x] Create a checkout.html
- [x] Link checkout templates to a view and urls
- [x] Checkout items are displayed with the price and subtotal 
- [x] Grand total is displayed
- [x] Page is fully responsive

**Comment by DarrachBarneveld** [comment]
Checkout page is fully styled and performs as intended
