### ISSUE TITLE
User Story: Order Line Item Model

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#35]
As a **developer**, I can view and manage line items within orders to track my purchase accurately and efficiently.

**Acceptance Criteria:**
1. Admin can see line items within orders
2. The line item contains the quantity, price and discounts of the order
3. The line items linked directly to an order

**Tasks**
- [x] Create an order line item 
- [x] Orderline items calculate the total of the quantity of items
- [x] Order line items shows price of individual items
- [x] Order Line items can be of any item

**Comment by DarrachBarneveld** [comment]
OrderLine item model created and linked to orders. This users a generic content type as referenced in the django frameworks documentation https://docs.djangoproject.com/en/5.0/ref/contrib/contenttypes/
