### ISSUE TITLE
User Story: Ordering Items

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#36]
As a **User**, I can securely process my order based on the checkout so that I can buy products from the store

**Acceptance Criteria:**
1. An Order form takes necessary user information
2. Stripe is used for payment processing of this order
3. An order is saved to the Database after success with items and user info
4. The cart is emptied after checkout success

**Tasks**
- [x] Create an Order Form
- [x] Link the order form in the checkout template
- [x] When the form is completed and pay now is clicked the order is processed
- [x] Save order to DB on success
- [x] Notify user based on outcome of checkout

**Comment by DarrachBarneveld** [comment]
Order are created upon successful checkout and via stripe webhooks
