### ISSUE TITLE
User Story: Stripe Payments

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#37]
As a **Developer**, I can securely complete my payment using Stripe integration with webhooks, ensuring that my transaction is protected and verified.

**Acceptance Criteria:**
1. Stripe Card payment option is rendered to order form
2. Users can enter a payment or test card
3. Stripe pid is added to order
4. Stripe webhook is utilised to ensure order creation based on payment intent success/charge

**Tasks**
- [x] Create a stripe element
- [x] Add stripe payment intent id to form with javascript
- [x] Ensure client secret is added to each order
- [x] Create a webhook handler for payment events
- [x] Ensure webhook creates orders whenever a payment intent succeeds
- [x] Add necessary config vars to env.py

**Comment by DarrachBarneveld** [comment]
Stripe payments perform independent of form submission. Webhooks handle and create orders in case of errors on front end
