### ISSUE TITLE
User Story: Sale/Subscription Discounts

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#40]
As a **User**, I can get sales and member discounts so that I can get items at a better price

**Acceptance Criteria:**
1. Users get discounted price on sale items
2. Users get discounted price when members
3. Users get discount if membership is in cart
4. Price breakdown is clearly presented

**Tasks**
- [x] Create subscription discount functions
- [x] Add methods to order model to account for discounts
- [x] Reflect all discounts in cart and checkout UI
- [x] The total accounts for final price

**Comment by DarrachBarneveld** [comment]
Subscription discounts are shown in confirmation, cart and checkout
