### ISSUE TITLE
User Story: Remove Membership

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#41]
As a **User**, I can remove my active membership so that I can opt out of payments

**Acceptance Criteria:**
1. Add a remove membership button
2. Render UI to display active membership
3. Clicking on unsubscribe brings a confirmation model
4. On confirm a subscription is remove

**Tasks**
- [x] Create a confirmation modal
- [x] On confirm remove the active and cart subscription from the user profile
- [x] Render UI to display no more active membership

**Comment by DarrachBarneveld** [comment]
Confirmation modal appears, confirming action removes subscription
