### ISSUE TITLE
User Story: Profile Page

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#42]
As a **User**, I can visit a profile page so that I can view my personal details and update them

**Acceptance Criteria:**

1. User can access the profile page from the navigation menu.
2. The profile page displays my current profile information, including name and delivery address.
3. I can edit my name and delivery address fields on the profile page.
4. Upon saving changes, my profile information is updated and reflected across the application.

**Tasks**

- [x]  Implement the profile page UI using Django templates.
- [x]  Render the template via the views and create url path
- [x]  Fetch and display the user's current profile information from the database.
- [x]  Implement form validation to ensure accurate data entry.
- [x]  Implement backend functionality to update the user's profile information in the database.
- [x]  Only correct authenticated users fields are updated

**Comment by DarrachBarneveld** [comment]
Profile page created, showing update forms and past orders
