### ISSUE TITLE
User Story: My Courses

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#45]
As a **User**, I can access a my courses page where I can view all the courses I have bought or enrolled in, so that I can easily track my learning progress and access course materials.

**Acceptance Criteria:**

- I can access the my courses page from the navbar
- The page displays a list of all the courses I have bought or enrolled in.
- Each course in the list includes its title, instructor, and a brief description.

**Tasks**

- [x]  Implement the My Courses page UI .
- [x]  Link the template to a view and url.
- [x]  Fetch and display the list of courses bought or enrolled by the user from the database.
- [x]  Render the course preview cards and link to courses.

**Comment by DarrachBarneveld** [comment]
My courses section rendered previous bought courses, or all courses if on main subscription package
