### ISSUE TITLE
User Story: Order Confirmation Emails

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#47]
As a **User**, I can receive an order confirmation emails after successfully completing a purchase, so that I have a record of the transaction and can review the details of my order.

**Acceptance Criteria:**

1. After completing a purchase, I receive an order confirmation email containing details of the transaction.
2. The order confirmation email includes information such as order number, items purchased, quantities, prices, and total amount.
3. The order confirmation have a contact email, heading and text

**Tasks**
- [x] Link Gmail smpt to send automated emails
- [x]  Implement email notification system to send order confirmation emails after successful purchases.
- [x]  Design an email template text file for order confirmation containing details of the transaction.

**Comment by DarrachBarneveld** [comment]
Order confirmation emails functioning as expected. Linked to gmail account
