### ISSUE TITLE
User Story: Loading Spinner

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#48]
As a **User**, I can see a loading spinner so that I know my actions were registered and a result in pending

**Acceptance Criteria:**
1. A loading spinner overlay exists
2. A loading spinner is animated 
3. A loading spinner appears for all async tasks
4. A loading spinner disappears when an action is complete

**Tasks**
- [x] Create and style a loading spinner
- [x] Show the loading spinner whenever an action that requires time to complete is done
- [x] Hide the spinner on completion of this task

**Comment by DarrachBarneveld** [comment]
Loading spinner added on async pages - checkout
