### ISSUE TITLE
User Story: Membership Level

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#49]
As a **User**, I can see my current membership level so that I know what discounts I can avail of

**Acceptance Criteria:**
1. Users membership level is immediately noticeable on the navbar
2. The profile page shows the users membership level
3. The checkout and cart page shows the users membership level

**Tasks**
- [x] Render colour difference on profile navbar element based on membership  
- [x] Within the profile template render text describing the users membership level
- [x] Within the cart template render text describing the users membership level
- [x] Within the checkout template render text describing the users membership level

**Comment by DarrachBarneveld** [comment]
Membership shown across all relevant pages
