### ISSUE TITLE
User Story: Related Items

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#51]
As a **User**, I can discover related products and programs on the program page, so that I can explore additional resources or offerings that complement my current selection.

**Acceptance Criteria:**

1. When viewing a program/product page, I see a section titled related items
2. Each related item includes a brief description and a link to view more details or make a purchase/enrollment.
3. The related items are dynamically updated based on the content of the current program, ensuring relevance and accuracy.

**Tasks**
- [x]  Implement functionality to identify related items based on the current program/product.
- [x]  Design and implement UI components to display the related items section on the page.
- [x]  Develop logic to curate and display a relevant list of related items and not including main item
- [x]  Use pagination to ensure there are not too many items displayed

**Comment by DarrachBarneveld** [comment]
Related cards are rendered to product/product page. Uniform cards across both pages
