### ISSUE TITLE
TESTING.md

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#55]
A full catalogue of testing will be presented in this file. All manual testing will be adhere to the feature validator result guidelines

**Tasks**
- [x] Testing of all python code is documented 
- [x] Testing of all javascript code is documented 
- [x] Testing of all css is documented 
- [x] Testing of all html code is documented 
- [x] Responsiveness testing
- [x] Browser compatibility 
- [x] Lighthouse scores
- [x] Manual testing of each element and its expected outcome

**Comment by DarrachBarneveld** [comment]
All testing documented. 100% manual testing coverage and some automation coverage
