### ISSUE TITLE
User Story: SEO

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#64]
As a **developer**, I can configure SEO information about the website so that users can easily access content.

**Acceptance Criteria:**

1. All pages have semantic markup that passes validation
2. Each page has relevant meta keywords and description tags in the head
3. Each page contains as h1 and content is well structured

**Tasks**

- [x]  Implement relevant and descriptive meta titles and descriptions for all pages.
- [x]  Ensure proper use of semantic markup such as <h1> tags for product names and <p> tags for descriptions.
- [x]  Include structured data markup on product pages to provide additional context for search engines.

**Comment by DarrachBarneveld** [comment]
SEO main files and meta tags added
