### ISSUE TITLE
User Story: Responsive Layout

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#8]
As a user I want the website to be responsive so I can view it on multiple devices

**Tasks**
- [x] Determine the crucial components and areas of the website that require enhancement to ensure mobile responsiveness.
- [x] Design page layouts with a mobile first development approach
- [x] Use a combination of bootstrap, media queries and css modifications to ensure responsive behaviour
- [x] Perform website wide checks on different screen size resolutions and devices

**Comment by DarrachBarneveld** [comment]
All pages are responsive and tested on multiple devices
