### ISSUE TITLE
USER STORY: Multi App Planning

### ISSUE THREAD

**Issue by DarrachBarneveld** [DarrachBarneveld/ci-swag#9]
As a **developer**, I can plan out multiple apps that have clear separation of function so that a larger scale project can be broken down into smaller modules

**Tasks**
- [x] Create individual apps within the django project using that startapp command 
- [x] Create a cart app
- [x] Create a checkout app
- [x] Create a home app
- [x] Create a product app
- [x] Create a program app
- [x] Create a profile app
- [x] Create base components

**Comment by DarrachBarneveld** [comment]
All apps and associated template/static folders created
